[project]
name = "fairswipe-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.125.0",
    "jinja2>=3.1.6",
    "mercantile>=1.2.1",
    "uvicorn>=0.38.0",
]
